{
 "title": "Fullscreen Overview",
 "tags": [
  "starlink",
  "fullscreen",
  "overview"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "poi_category",
    "label": "POI Category",
    "query": "Departure & Arrival : departure\\,arrival, All POIs :  , Departure Only : departure, Arrival Only : arrival, Waypoints Only : waypoint, Alternates Only : alternate"
   }
  ]
 },
 "panels": [
  {
   "title": "UTC (Zulu)",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Washington DC",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tokyo",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Omaha",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Position",
   "type": "geomap",
   "gridPos": { "h": 23, "w": 18, "x": 0, "y": 3 },
   "targets": [
    { "expr": "starlink_dish_latitude_degrees", "legendFormat": "latitude" },
    {
     "expr": "starlink_dish_longitude_degrees",
     "legendFormat": "longitude"
    },
    { "expr": "starlink_dish_altitude_feet", "legendFormat": "altitude" },
    { "expr": "starlink_dish_heading_degrees", "legendFormat": "heading" },
    {
     "expr": "(starlink_dish_latitude_degrees and (((starlink_dish_longitude_degrees + 180) % 360) - 180) < 0) or (starlink_dish_latitude_degrees unless count_over_time(((((starlink_dish_longitude_degrees + 180) % 360) - 180) < 0)[$__range:] @ ${__to:date:seconds}) > 0)",
     "legendFormat": "latitude_history"
    },
    {
     "expr": "((((starlink_dish_longitude_degrees + 180) % 360) - 180) < 0) or ((((starlink_dish_longitude_degrees + 180) % 360) - 180) unless count_over_time(((((starlink_dish_longitude_degrees + 180) % 360) - 180) < 0)[$__range:] @ ${__to:date:seconds}) > 0)",
     "legendFormat": "longitude_history"
    },
    {
     "cacheDurationSeconds": 1,
     "parser": "json",
     "root_selector": "pois",
     "source": "url",
     "type": "json",
     "url": "/api/pois/etas?category=${poi_category}",
     "urlOptions": {
      "params": [
       { "name": "category", "value": "${poi_category}" }
      ]
     },
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    },
    {
     "cacheDurationSeconds": 5,
     "parser": "backend",
     "root_selector": "coordinates",
     "source": "url",
     "type": "json",
     "url": "/api/route/coordinates/west",
     "urlOptions": {
      "params": []
     },
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    },
    {
     "cacheDurationSeconds": 5,
     "parser": "backend",
     "root_selector": "coordinates",
     "source": "url",
     "type": "json",
     "url": "/api/route/coordinates/east",
     "urlOptions": {
      "params": []
     },
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    },
    {
     "expr": "(starlink_dish_latitude_degrees and (((starlink_dish_longitude_degrees + 180) % 360) - 180) >= 0) or (starlink_dish_latitude_degrees unless count_over_time(((((starlink_dish_longitude_degrees + 180) % 360) - 180) >= 0)[$__range:] @ ${__to:date:seconds}) > 0)",
     "legendFormat": "latitude_history"
    },
    {
     "expr": "((((starlink_dish_longitude_degrees + 180) % 360) - 180) >= 0) or ((((starlink_dish_longitude_degrees + 180) % 360) - 180) unless count_over_time(((((starlink_dish_longitude_degrees + 180) % 360) - 180) >= 0)[$__range:] @ ${__to:date:seconds}) > 0)",
     "legendFormat": "longitude_history"
    },
    {
     "cacheDurationSeconds": 1,
     "parser": "backend",
     "root_selector": "pois",
     "source": "url",
     "type": "json",
     "url": "/api/pois/etas?category=satellite",
     "urlOptions": {
      "params": [
       { "name": "category", "value": "${poi_category}" }
      ]
     },
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    },
    {
     "cacheDurationSeconds": 1,
     "parser": "backend",
     "root_selector": "pois",
     "source": "url",
     "type": "json",
     "url": "/api/pois/etas?category=mission-event",
     "urlOptions": {
      "params": [
       { "name": "category", "value": "${poi_category}" }
      ]
     },
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    },
    {
     "cacheDurationSeconds": 1,
     "parser": "backend",
     "root_selector": "coordinates",
     "source": "url",
     "type": "json",
     "url": "/api/active-x-link?state=normal",
     "urlOptions": {
      "params": []
     },
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    },
    {
     "cacheDurationSeconds": 1,
     "parser": "backend",
     "root_selector": "coordinates",
     "source": "url",
     "type": "json",
     "url": "/api/active-x-link?state=warning",
     "urlOptions": {
      "params": []
     },
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    },
    {
     "expr": "starlink_ground_entry_point_latitude_degrees",
     "legendFormat": "ground_entry_latitude"
    },
    {
     "expr": "starlink_ground_entry_point_longitude_degrees",
     "legendFormat": "ground_entry_longitude"
    }
   ]
  },
  {
   "title": "POI Quick Reference (Top 5)",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "cacheDurationSeconds": 1,
     "pagination": {
      "enabled": false
     },
     "parser": "json",
     "root_selector": "pois",
     "source": "url",
     "type": "json",
     "url": "/api/pois/etas?category=arrival,departure,mission-event",
     "urlOptions": {
      "params": [
       { "name": "latitude", "value": "41.6" },
       { "name": "longitude", "value": "-74.0" },
       { "name": "speed_knots", "value": "67" },
       { "name": "category", "value": "${poi_category}" }
      ]
     },
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "starlink_network_latency_ms_current",
     "legendFormat": "Current"
    },
    {
     "expr": "min_over_time(starlink_network_latency_ms_current[5m])",
     "legendFormat": "Min (5m)"
    },
    {
     "expr": "avg_over_time(starlink_network_latency_ms_current[5m])",
     "legendFormat": "Avg (5m)"
    },
    {
     "expr": "max_over_time(starlink_network_latency_ms_current[5m])",
     "legendFormat": "Max (5m)"
    }
   ]
  },
  {
   "title": "Download/Upload Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "starlink_network_throughput_up_mbps_current * -1",
     "legendFormat": "Upload"
    },
    {
     "expr": "starlink_network_throughput_down_mbps_current",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Ground Entry Point",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_ground_entry_point_info",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Obstruction %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dish_obstruction_percent",
     "legendFormat": "Obstruction"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "starlink_network_packet_loss_percent",
     "legendFormat": "Packet Loss"
    }
   ]
  }
 ]
}