"""
Backward compatibility wrapper for metrics module.

This file maintains backward compatibility by re-exporting all metrics
from the new app.core.metrics module structure.

DEPRECATED: Import from app.core.metrics instead.
"""

# Re-export everything from the new metrics module
from app.core.metrics import *  # noqa: F401, F403

__all__ = [
    "REGISTRY",
    "_current_position",
    "starlink_device_location",
    "starlink_dish_latitude_degrees",
    "starlink_dish_longitude_degrees",
    "starlink_dish_altitude_feet",
    "starlink_dish_speed_knots",
    "starlink_dish_heading_degrees",
    "starlink_network_latency_ms_current",
    "starlink_network_throughput_down_mbps_current",
    "starlink_network_throughput_up_mbps_current",
    "starlink_network_packet_loss_percent",
    "starlink_network_latency_ms",
    "starlink_network_throughput_down_mbps",
    "starlink_network_throughput_up_mbps",
    "starlink_dish_obstruction_percent",
    "starlink_signal_quality_percent",
    "starlink_service_info",
    "starlink_mode_info",
    "starlink_uptime_seconds",
    "starlink_dish_uptime_seconds",
    "starlink_dish_thermal_throttle",
    "starlink_dish_outage_active",
    "starlink_connection_attempts_total",
    "starlink_connection_failures_total",
    "starlink_outage_events_total",
    "starlink_thermal_events_total",
    "starlink_eta_poi_seconds",
    "starlink_distance_to_poi_meters",
    "starlink_flight_phase",
    "starlink_eta_mode",
    "starlink_flight_departure_time_unix",
    "starlink_flight_arrival_time_unix",
    "starlink_time_until_departure_seconds",
    "starlink_route_progress_percent",
    "starlink_current_waypoint_index",
    "starlink_route_has_timing_data",
    "starlink_route_total_duration_seconds",
    "starlink_route_departure_time_unix",
    "starlink_route_arrival_time_unix",
    "starlink_route_segment_count_with_timing",
    "starlink_eta_to_waypoint_seconds",
    "starlink_distance_to_waypoint_meters",
    "starlink_route_segment_speed_knots",
    "starlink_metrics_scrape_duration_seconds",
    "starlink_metrics_generation_errors_total",
    "starlink_metrics_last_update_timestamp_seconds",
    "mission_active_info",
    "mission_phase_state",
    "mission_next_conflict_seconds",
    "mission_timeline_generated_timestamp",
    "mission_comm_state",
    "mission_degraded_seconds",
    "mission_critical_seconds",
    "simulation_updates_total",
    "simulation_errors_total",
    "update_metrics_from_telemetry",
    "clear_telemetry_metrics",
    "set_service_info",
    "update_mission_active_metric",
    "clear_mission_metrics",
    "update_mission_phase_metric",
    "update_mission_timeline_timestamp",
    "update_mission_comm_state_metric",
    "update_mission_duration_metrics",
    "update_mission_next_conflict_metric",
]
