FROM grafana/grafana:12.0.2

COPY monitoring/grafana/provisioning /etc/grafana/provisioning
COPY monitoring/grafana/custom-icons/chevron-up.svg /usr/share/grafana/public/img/icons/marker/chevron-up.svg
